version: '2'
services:
  1a_login_ms:
    build: .
    ports:
     - "5000:5000"
  1a_login_db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: alejo
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: users
      MYSQL_HOST: 1a_login_db
      